baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Northburns' GW2 \"no nuance notes\""
theme = 'hugo-theme-relearn'

[params]
  themeVariant = 'relearn-light'

[caches]
  [caches.images]
    dir = ':cacheDir/images'