# https://taskfile.dev

version: '3'

vars:
  DIR: assets/data/gw2-api
  URL: https://api.guildwars2.com/v2
  CURL_RETRY: --retry 10

tasks:

  default:
    cmds:
    - task: js-bundle
    - task: hugo-server

  install:
    desc: Install needed stuff
    cmds:
    - scoop install charm-gum jq

  hugo-server:
    desc: Runs Hugo server (with drafts)
    cmds:
    - hugo server -D --disableLiveReload
  
  init:
    desc: initialize script project
    dir: _scripts
    cmds:
    - yarn install
  
  do-api-all:
    desc: Do all APIs in one go
    cmds:
    - { task: do-api-one, vars: { API: currencies,              DIR: currencies,        KEY: id, NAME: name  } }
    - { task: do-api-one, vars: { API: items,                   DIR: items,             KEY: id, NAME: name  } }
    - { task: do-api-one, vars: { API: achievements,            DIR: achievements,      KEY: id, NAME: name  } }
    - { task: do-api-one, vars: { API: achievements/groups,     DIR: achGroups,         KEY: id, NAME: name  } }
    - { task: do-api-one, vars: { API: achievements/categories, DIR: achCats,           KEY: id, NAME: name  } }
    - { task: do-api-one, vars: { API: masteries,               DIR: masteries,         KEY: id, NAME: name  } }
    - { task: do-api-one, vars: { API: skills,                  DIR: skills,            KEY: id, NAME: name  } }
    - { task: do-api-one, vars: { API: legends,                 DIR: legends,           KEY: id, NAME: id    } }
    - { task: do-api-one, vars: { API: traits,                  DIR: traits,            KEY: id, NAME: name  } }
    - { task: do-api-one, vars: { API: files,                   DIR: files,             KEY: id, NAME: id    } }
    - { task: do-api-one, vars: { API: professions,             DIR: professions,       KEY: id, NAME: name  } }
    - { task: do-api-one, vars: { API: specializations,         DIR: specializations,   KEY: id, NAME: name  } }

  do-api-one:
    requires: { vars: [API, DIR, KEY, NAME] }
    dir: _scripts
    cmds:
    - yarn run do-api {{.API}} {{.DIR}} {{.KEY}} {{.NAME}}

  js-bundle:
    desc: Bundle my js
    dir: _scripts
    cmds:
    - yarn run bundle
    - cp dist/* ../assets/js/
    - cp node_modules/tabulator-tables/dist/css/tabulator.css ../assets/css/

  js-dl-tp-history:
    desc: Downloads TP history data (last 7 days) from ApiWars
    dir: _scripts
    cmds:
    - yarn run tp-history
